# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Safa Creations 
name: Safa Creations LTD
email: zaidalissaalmaliki@gmail.com
description: Intersection between Machine Learning and Software Engineering

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg


baseurl: / # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: https://www.safacreations.net # the url of your site
medium: https://medium.com/@zaidalissa/
github:  https://github.com/nawter

google_analytics_tracking_id:  UA-129904707-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks amigo!

medium_username: zaidalissa 

theme: jekyll-material-theme

# Build settings
markdown: kramdown

permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sass-converter
  - jekyll-minifier

collections:
  - medium_posts

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: angularjs
  - name: apache
  - name: atom
  - name: bitbucket
  - name: c
  - name: confluence
  - name: cplusplus
  - name: cucumber
  - name: django
  - name: debian
  - name: docker
  - name: gimp
  - name: git
  - name: github
  - name: gitlab
  - name: html5
  - name: inkscape
  - name: itellij
  - name: java
  - name: javascript
  - name: linux
  - name: mongodb
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: oracle
  - name: postgresql
  - name: python
  - name: pycharm
  - name: redis
  - name: ruby
  - name: rubymine
  - name: sass
  - name: slack
  - name: sourcetree
  - name: ssh
  - name: tomcat
  - name: trello
  - name: ubuntu
  - name: vim
  - name: wordpress

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

