# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Safa Creations 
name: Safa Creations LTD
email: zaidalissaalmaliki@gmail.com
description: Intersection between Machine Learning and Software Engineering

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg


github: https://github.com/nawter
medium: https://medium.com



baseurl: / # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: https://www.safacreations.net # the url of your site
medium: https://medium.com/@zaidalissa/
github:  https://github.com/nawter

#google_analytics_tracking_id: UA-110869900-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

#cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

#cookie_accept_message: Thank you amigo!

medium_username: zaidalissa 





# Build settings
markdown: kramdown

permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sass-converter
  - jekyll-minifier

collections:
  - medium_posts
